remote_theme: kitian616/jekyll-TeXt-theme

collections:
  transcripts:
    output: true
    layout: article

exclude:
  - scripts

## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
title   : Transkrypcje po polsku
description: > # this means to ignore newlines until "Language & timezone"
  Transkrypcje wartościowych filmów przetłumaczone na język polski
## => Language and Timezone
##############################
lang: pl
timezone: Europe/Warsaw # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


search:
  provider: default

defaults:
  - scope:
      path: ""
      type: transcripts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
