remote_theme: kitian616/jekyll-TeXt-theme

collections:
  transcripts:
    output: true

## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
title   : Transkrypcje po polsku
description: > # this means to ignore newlines until "Language & timezone"
  Transkrypcje wartościowych filmów przetłumaczone na język polski
## => Language and Timezone
##############################
lang: pl
timezone: Europe/Warsaw # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


